# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-16 14:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_category_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='img_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gallery.Category'),
        ),
        migrations.AddField(
            model_name='image',
            name='img_location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gallery.Location'),
        ),
    ]
